binop_separator = "Back"
control_brace_style = "ClosingNextLine"
empty_item_single_line = true
enum_discrim_align_threshold = 40
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
format_macro_matchers = false
format_macro_bodies = true
format_strings = false
hard_tabs = true
imports_layout = "HorizontalVertical"
indent_style = "Block"
match_arm_blocks = true
match_block_trailing_comma = false
merge_derives = true
imports_granularity = "Preserve"
newline_style = "Unix"
normalize_comments = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
space_after_colon = true
space_before_colon = false
# space_around_ranges = false
struct_lit_single_line = true
tab_spaces = 4
trailing_semicolon = true
type_punctuation_density = "Wide"
use_try_shorthand = false
version = "Two"
