binop_separator = "Back"
control_brace_style = "ClosingNextLine"
use_small_heuristics = "Off"
empty_item_single_line = true
enum_discrim_align_threshold = 0
fn_single_line = false
force_explicit_abi = true
force_multiline_blocks = false
format_code_in_doc_comments = true
format_macro_matchers = false
format_macro_bodies = true
format_strings = false
hard_tabs = false
imports_layout = "HorizontalVertical"
indent_style = "Block"
match_arm_blocks = true
match_block_trailing_comma = false
remove_nested_parens = true
reorder_imports = true
reorder_modules = true
space_after_colon = true
space_before_colon = true
struct_lit_single_line = true
tab_spaces = 4
trailing_semicolon = true
use_try_shorthand = false
